### ISSUE TITLE
Connected to stream deck plugin

### ISSUE THREAD

**Issue by ptahbe** [nguyenquyhy/Flight-Tracker-StreamDeck#34]
Hi,

Since the last update (0.8) I get a message in MSFS  stating "Connected to stream deck plugin" whenever I press a button.

![image](https://user-images.githubusercontent.com/4303590/96270675-4462c200-0fcc-11eb-9881-413b8fe7241c.png)

I know this has (probably) nothing to do with the plugin, but maybe other people have this issue too.

Does anyone know where I can turn this message off.

**Comment by rkantos** [comment]
This is probably actually related to #24 .. It happens especially if your button / SimConnect variable isn't available or otherwise not working. I recommend checking out recently added or modified buttons and remove them or start with a new profile which only includes the basic buttons.

**Comment by nguyenquyhy** [comment]
Everytime you see that message, it means the plugin receive an error from SimConnect and try to reconnect. As rkantos said, if it can due to some wrong variables.

You can see the actual error in the log files at "%appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin\flightstreamdeck*.log".

**Comment by Der-Matze** [comment]
Get the same message loop in 0.8, not that often as in pre-0.7 but 0.7 was the most stable. Here's one of the exceptions i found in the log.

`2020-10-17 15:18:18.637 +02:00 [INF] RegisterValue "LIGHT_NAV" LIGHT NAV
2020-10-17 15:18:18.637 +02:00 [INF] RegisterValue "LIGHT_LANDING" LIGHT LANDING
2020-10-17 15:18:18.637 +02:00 [INF] RegisterValue "GEAR_TOTAL_PCT_EXTENDED" GEAR TOTAL PCT EXTENDED
2020-10-17 15:18:18.944 +02:00 [ERR] Exception received
System.Runtime.InteropServices.COMException (0xC00000B0): 0xC00000B0
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.FlightSimulator.SimConnect.SimConnect.ReceiveDispatch(SignalProcDelegate pfcnSignal)
   at FlightStreamDeck.SimConnectFSX.SimConnectFlightConnector.HandleSimConnectEvents(IntPtr hWnd, Int32 message, IntPtr wParam, IntPtr lParam, Boolean& isHandled) in D:\Hy\Codes\_nguyenquyhy\FlightStreamDeck\FlightStreamDeck.SimConnectFSX\SimConnectFlightConnector.cs:line 76
2020-10-17 15:18:19.059 +02:00 [INF] RegisterValue "AUTOPILOT_ALTITUDE_LOCK" AUTOPILOT ALTITUDE LOCK
2020-10-17 15:18:19.059 +02:00 [INF] RegisterValue "AUTOPILOT_YAW_DAMPER" AUTOPILOT YAW DAMPER
2020-10-17 15:18:19.059 +02:00 [INF] RegisterValue "AUTOPILOT_VERTICAL_HOLD" AUTOPILOT VERTICAL HOLD
2020-10-17 15:18:19.059 +02:00 [INF] RegisterValue "AUTOPILOT_FLIGHT_DIRECTOR_ACTIVE" AUTOPILOT FLIGHT DIRECTOR ACTIVE
2020-10-17 15:18:19.059 +02:00 [INF] RegisterValue "COM_ACTIVE_FREQUENCY__1" COM ACTIVE FREQUENCY:1`

**Comment by ptahbe** [comment]
I got the same error in the logs :

System.Runtime.InteropServices.COMException (0xC00000B0): 0xC00000B0
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.FlightSimulator.SimConnect.SimConnect.ReceiveDispatch(SignalProcDelegate pfcnSignal)
   at FlightStreamDeck.SimConnectFSX.SimConnectFlightConnector.HandleSimConnectEvents(IntPtr hWnd, Int32 message, IntPtr wParam, IntPtr lParam, Boolean& isHandled) in D:\Hy\Codes\_nguyenquyhy\FlightStreamDeck\FlightStreamDeck.SimConnectFSX\SimConnectFlightConnector.cs:line 76

Today I got the error 1 time (so far)
Yesterday I played for several hours and got the error more than 300 times.

**Comment by nguyenquyhy** [comment]
Would you mind export the profile and share with me? I don't use a lot of Generic buttons so I might not encountered all those issues yet?

Also, do you usually hold any buttons? For my profile, the disconnection only happen when I have to hold a button for quite a while or if I have to spam a button relatively quickly.

**Comment by Der-Matze** [comment]
Here's my profile, let me know if you need the button graphics too.

https://drive.google.com/file/d/1e89FWU88X1F1mFW3NC4wlVBAb2uESD9B/view?usp=sharing

**Comment by nguyenquyhy** [comment]
I don't see anything strange with your profile, so probably it is just general instability of SimConnect.
And actually, 0.7 to 0.8 doesn't have any changes regarding SimConnect connection, while 0.6 to 0.7 does have some stability improvement on error recovery, so I don't think 0.7 would be more stable than 0.8. 

The COMException you see doesn't contains any details on the error (even the error code is always 0xC00000B0). However, if you look around that log line, you might see something like `Exception received: "UNRECOGNIZED_ID"` or `Exception received: "EVENT_ID_DUPLICATE"`, which can cause SimConnect issue. 
For some other cases such as holding the +/- button for too long, SimConnect just throws COMException without providing any information beforehand.

For now I am still not very sure what you issue you are encountering in the first place, but I am aware of a problem that not all variables are registered correctly after a reconnection, so I'll look into fixing that for 1.10.

**Comment by Der-Matze** [comment]
Don't worry, the overall stability is very good and a huge step forward in comparison to 0.6. Let's just observe the issue and hope it gets fixed by some simconnect updates.

**Comment by ptahbe** [comment]
I just had it again. I have this issue whenever I press a button many times in a few seconds or when I hold a button. For example when VS is at +1000 and I want it to go to -1000. For this I use a predefined button "Decrease value" with the function "Vertical Speed"

This is mu profile
https://drive.google.com/file/d/1SdsiRsYecForrOgytkBJjIwunNNwicV9/view?usp=sharing

**Comment by nguyenquyhy** [comment]
Yep that's the SimConnect issue I was talking about. If you hold a button for a while, SimConnect can fail randomly. Sometimes, you can just ignore that failure, but sometimes you need to force a reconnection or SimConnect will stop reacting to any event. Right now there is no indication from the error to know which is which, so I always force a reconnection.

That couples with a current bug of Generic buttons on reconnection may cause a constant error/reconnection (and then the Connected message in sim) on every button press. I'll try to fix that.

**Comment by nguyenquyhy** [comment]
Please try again with version 0.11.
