### ISSUE TITLE
CTD long-haul

### ISSUE THREAD

**Issue by DavidEGTE** [nguyenquyhy/Flight-Tracker-StreamDeck#410]
SDP 0.51.0 MSFS 1.34.16.0
MSFS just CTD, doing a long-haul flight often near destination
no profile is used as I'm with Asobo 747-8i

[flightstreamdeck20231112.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/13349521/flightstreamdeck20231112.log)
[flightstreamdeck20231113.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/13349523/flightstreamdeck20231113.log)
[flightstreamdeck20231114.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/13349524/flightstreamdeck20231114.log)

**Comment by wagoozen1** [comment]
I got the exact same issue just out of the blue, i did many long haul flights, and today it happens. What i find strange is thatits mention in D:\Hy\Codes\_nguyenquyhy\FlightStreamDeck\FlightStreamDeck.SimConnectFSX\SimConnectFlightConnector.cs:line 80.

I dont have a D:\Hy, so this might be hardcoded?

**Comment by Longhaulpilot** [comment]
Hello,

i experience the same problem as described above. I´m using P3Dv5.3 and would appreciate a statement to this issue or a short description how we can solve this problem by ourself. Thank You!

**Comment by MANFahrer-GF** [comment]
MSFS 24 CTD

Category: FlightStreamDeck.SimConnectFSX.SimConnectFlightConnector
EventId: 0

Exception received

Exception: 
System.Runtime.InteropServices.COMException (0xC000014B): 0xC000014B
   at Microsoft.FlightSimulator.SimConnect.SimConnect.ReceiveDispatch(SignalProcDelegate pfcnSignal)
   at FlightStreamDeck.SimConnectFSX.SimConnectFlightConnector.HandleSimConnectEvents(Int32 message, Boolean& isHandled) in E:\Codes\_nguyenquyhy\FlightStreamDeck\FlightStreamDeck.SimConnectFSX\SimConnectFlightConnector.cs:line 64

**Comment by nguyenquyhy** [comment]
> MSFS 24 CTD
> 
> Category: FlightStreamDeck.SimConnectFSX.SimConnectFlightConnector
> EventId: 0
> 
> Exception received
> 
> Exception: 
> System.Runtime.InteropServices.COMException (0xC000014B): 0xC000014B
>    at Microsoft.FlightSimulator.SimConnect.SimConnect.ReceiveDispatch(SignalProcDelegate pfcnSignal)
>    at FlightStreamDeck.SimConnectFSX.SimConnectFlightConnector.HandleSimConnectEvents(Int32 message, Boolean& isHandled) in E:\Codes\_nguyenquyhy\FlightStreamDeck\FlightStreamDeck.SimConnectFSX\SimConnectFlightConnector.cs:line 64
> 

This basically just indicates that the connection to the sim was terminated unexpectedly, in this case, because the sim crashed. I highly doubt the plugin has anything to do with the crash.
