### ISSUE TITLE
Exception in SimConnectFlightConnector.cs

### ISSUE THREAD

**Issue by aviapics** [nguyenquyhy/Flight-Tracker-StreamDeck#422]
Hi,
I have quite often a crash on SimConnectFlightConnector.cs causing the game to stop.
Here are my infos:
StreamDeck XL version 6.52
Plugin flight tracker 0.52
MSFS version Microsoft Store up to date
Profiles
[Stream Deck - 17-03-2024 - 17-27.zip](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/14628111/Stream.Deck.-.17-03-2024.-.17-27.zip)
Log file
[flightstreamdeck20240317.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/14628113/flightstreamdeck20240317.log)

Windows EventWatcher log:

Category: FlightStreamDeck.SimConnectFSX.SimConnectFlightConnector
EventId: 0

Exception received

Exception: 
System.Runtime.InteropServices.COMException (0xC000014B): 0xC000014B
   at Microsoft.FlightSimulator.SimConnect.SimConnect.ReceiveDispatch(SignalProcDelegate pfcnSignal)
   at FlightStreamDeck.SimConnectFSX.SimConnectFlightConnector.HandleSimConnectEvents(Int32 message, Boolean& isHandled) in D:\Hy\Codes\_nguyenquyhy\FlightStreamDeck\FlightStreamDeck.SimConnectFSX\SimConnectFlightConnector.cs:line 80

Thanks a lot for your help

**Comment by jc14** [comment]
Recently, I've been getting this bug quite often. The sim crashes to desktop every 3 load into a flight or so. Same error as listed above.

**Comment by datendenker** [comment]
Exactly the same problem here, With MSFS2024 SU 1 and SU 2 beta,

**Comment by nguyenquyhy** [comment]
0xC000014B simply means the sim crashes for other reasons, so the connection from the plugin to the sim stopped unexpectedly.
